/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --types ./macbook.glb 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube023: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube031: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube033: THREE.Mesh
    Cube033_1: THREE.Mesh
    Cube033_2: THREE.Mesh
    Cube033_3: THREE.Mesh
    Cube033_4: THREE.Mesh
    Cube033_5: THREE.Mesh
    Cube033_6: THREE.Mesh
    Cube033_7: THREE.Mesh
    Cube033_8: THREE.Mesh
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube034_2: THREE.Mesh
  }
  materials: {
    body: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
    key: THREE.MeshStandardMaterial
    ['key.002']: THREE.MeshStandardMaterial
    Bambu_UI_Mat: THREE.MeshStandardMaterial
    ['black.002']: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    Glass_Mat: THREE.MeshPhysicalMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshPhysicalMaterial
    ['glass.003']: THREE.MeshPhysicalMaterial
    ['Apple-logo']: THREE.MeshStandardMaterial
    Dark: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/macbook.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[5.24, 1.185, -1.726]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.body} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['black.001']} />
      </group>
      <group position={[5.646, 1.186, -1.607]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.key} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['key.002']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials.Bambu_UI_Mat} />
      </group>
      <group position={[5.641, 1.173, -1.776]} rotation={[1.333, 0, 0]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials.body} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials.screen} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials.dark} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials.Glass_Mat} />
        <mesh geometry={nodes.Cube033_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube033_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube033_7.geometry} material={materials['glass.003']} />
        <mesh geometry={nodes.Cube033_8.geometry} material={materials['Apple-logo']} />
      </group>
      <group position={[5.641, 1.176, -1.517]} rotation={[-0.016, 0, 0]}>
        <mesh geometry={nodes.Cube034.geometry} material={materials.body} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials.Dark} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/macbook.glb')
