/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --types ./office-room.glb 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName = "CINEMA_4D_Main" | "TimeLineAnimation";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Books: THREE.Mesh;
		Paper: THREE.Mesh;
		PenHolderMesh: THREE.Mesh;
		CameraOutline: THREE.Mesh;
		iPhoneLences: THREE.Mesh;
		MainPhoneCase: THREE.Mesh;
		PLARollHolder: THREE.Mesh;
		Solder_curve: THREE.Mesh;
		Solder_mesh: THREE.Mesh;
		Solder_roll006: THREE.Mesh;
		Solder_curve003: THREE.Mesh;
		Solder_mesh003: THREE.Mesh;
		Solder_roll003: THREE.Mesh;
		Solder_curve001: THREE.Mesh;
		Solder_mesh001: THREE.Mesh;
		Solder_roll004: THREE.Mesh;
		Solder_curve002: THREE.Mesh;
		Solder_mesh002: THREE.Mesh;
		OldMacbookHousing: THREE.Mesh;
		BeigeBook: THREE.Mesh;
		BlackBook: THREE.Mesh;
		Cube107: THREE.Mesh;
		Cube108: THREE.Mesh;
		Cube109: THREE.Mesh;
		Cube110: THREE.Mesh;
		Cube111: THREE.Mesh;
		Cube112: THREE.Mesh;
		Cube113: THREE.Mesh;
		Cube114: THREE.Mesh;
		Cube116: THREE.Mesh;
		Cube117: THREE.Mesh;
		Cube118: THREE.Mesh;
		Cube119: THREE.Mesh;
		Cube122: THREE.Mesh;
		Cube125: THREE.Mesh;
		Cube126: THREE.Mesh;
		GreenBook: THREE.Mesh;
		GreyBook: THREE.Mesh;
		RedBook: THREE.Mesh;
		WhiteBook: THREE.Mesh;
		MusterboxFaecher: THREE.Mesh;
		MusterboxFaecherPages: THREE.Mesh;
		MusterboxBoden: THREE.Mesh;
		MusterboxInside: THREE.Mesh;
		MusterboxDeckel: THREE.Mesh;
		MusterboxDeckelRightSide: THREE.Mesh;
		MusterboxLasche: THREE.Mesh;
		Mesh_3: THREE.Mesh;
		MusterboxGriff: THREE.Mesh;
		MusterboxBox01: THREE.Mesh;
		MusterboxBox02: THREE.Mesh;
		MusterboxBox03: THREE.Mesh;
		MusterboxBox04: THREE.Mesh;
		MusterboxBox05: THREE.Mesh;
		MusterboxBox06: THREE.Mesh;
		MusterboxBox07: THREE.Mesh;
		MusterboxBox08: THREE.Mesh;
		MusterboxBox09: THREE.Mesh;
		MusterboxBox10: THREE.Mesh;
		MusterboxBox11: THREE.Mesh;
		MusterboxBox12: THREE.Mesh;
		MusterboxBox13: THREE.Mesh;
		MusterboxBox14: THREE.Mesh;
		MusterboxBox15: THREE.Mesh;
		MusterboxBox16: THREE.Mesh;
		MusterboxBox17: THREE.Mesh;
		MusterboxBox18: THREE.Mesh;
		MusterboxBox19: THREE.Mesh;
		MusterboxBox20: THREE.Mesh;
		MusterboxBox21: THREE.Mesh;
		MusterboxBox22: THREE.Mesh;
		MusterboxBox23: THREE.Mesh;
		MusterboxBox24: THREE.Mesh;
		FCBoxKuehlerBottomPart: THREE.Mesh;
		FCBoxKuehlerBackPart: THREE.Mesh;
		FCBoxKuehlerSidePart: THREE.Mesh;
		mesh_1: THREE.Mesh;
		mesh_11: THREE.Mesh;
		mesh_12: THREE.Mesh;
		mesh_13: THREE.Mesh;
		mesh_14: THREE.Mesh;
		mesh_15: THREE.Mesh;
		mesh_4: THREE.Mesh;
		mesh_5: THREE.Mesh;
		mesh_19: THREE.Mesh;
		mesh_2: THREE.Mesh;
		mesh_3: THREE.Mesh;
		mesh_17: THREE.Mesh;
		mesh_6: THREE.Mesh;
		mesh_7: THREE.Mesh;
		mesh_8: THREE.Mesh;
		mesh_9: THREE.Mesh;
		FCBoxDBottomPart: THREE.Mesh;
		FCBoxDBackPart: THREE.Mesh;
		FCBoxDSidePart: THREE.Mesh;
		FCBoxHBottomPart: THREE.Mesh;
		FCBoxHBackPart: THREE.Mesh;
		FCBoxHSidePart: THREE.Mesh;
		FCBoxBBottomPart: THREE.Mesh;
		FCBoxBBackPart: THREE.Mesh;
		FCBoxBSidePart: THREE.Mesh;
		Flower1: THREE.Mesh;
		Flower2: THREE.Mesh;
		Flower3: THREE.Mesh;
		Flower4: THREE.Mesh;
		vase: THREE.Mesh;
		FloorLamp_Bulb: THREE.Mesh;
		FloorLamp_Cover: THREE.Mesh;
		FloorLamp_Stem: THREE.Mesh;
		Room: THREE.Mesh;
		Floor: THREE.Mesh;
		BackWall: THREE.Mesh;
		FrontWall: THREE.Mesh;
		WindowWall: THREE.Mesh;
		Roof: THREE.Mesh;
		LeftWall: THREE.Mesh;
		DeskWorkingAreas: THREE.Mesh;
		DeskStands: THREE.Mesh;
		CupboardDoors: THREE.Mesh;
		CupboardOpeners: THREE.Mesh;
		Ventilation: THREE.Mesh;
		Keyboard: THREE.Mesh;
		Screen: THREE.Mesh;
		Housing: THREE.Mesh;
		Sit: THREE.Mesh;
		Cube017: THREE.Mesh;
		Cube018_1: THREE.Mesh;
		Cube019: THREE.Mesh;
		Cube020: THREE.Mesh;
		Cube021_1: THREE.Mesh;
		Cube029: THREE.Mesh;
		Cube030: THREE.Mesh;
		Cube031_1: THREE.Mesh;
		Handle002: THREE.Mesh;
		Plane006: THREE.Mesh;
		Plane007: THREE.Mesh;
		RightBackrestStrap: THREE.Mesh;
		LeftBackrestStrap: THREE.Mesh;
		Backrest: THREE.Mesh;
		BackrestController: THREE.Mesh;
		ChairStand: THREE.Mesh;
		BackrestPillow: THREE.Mesh;
		ChairRoll: THREE.Mesh;
		Organizer: THREE.Mesh;
		Base: THREE.Mesh;
		FirstController: THREE.Mesh;
		FrontOcculus: THREE.Mesh;
		BackOcculus: THREE.Mesh;
		bambuLabFrontDoor: THREE.Mesh;
		["bambu-lab-x1c-ui"]: THREE.Mesh;
		["bambu-lab-x1c-ui-display"]: THREE.Mesh;
		["bambu-lab-x1c"]: THREE.Mesh;
		["bambu-lab-x1c-logo"]: THREE.Mesh;
		bambuLabAMS: THREE.Mesh;
		bambuLabAMSTop: THREE.Mesh;
		PLARoll: THREE.Mesh;
		SecondRoll001: THREE.Mesh;
		SecondRoll002: THREE.Mesh;
		SecondRoll003: THREE.Mesh;
		["bambu-lab-x1c-nozzle"]: THREE.Mesh;
		["bambu-lab-x1c-nozzle-spike"]: THREE.Mesh;
		["bambu-lab-x1c--nozzle-rods"]: THREE.Mesh;
		["bambu-lab-x1c-nozzle-hole"]: THREE.Mesh;
		FolderDocuments: THREE.Mesh;
		Pool_balls_set: THREE.Mesh;
		RoofLamp: THREE.Mesh;
		DoorBase: THREE.Mesh;
		MainHandle: THREE.Mesh;
		WindowBorder: THREE.Mesh;
		WindowGlass: THREE.Mesh;
		Filing: THREE.Mesh;
		CoffeCupStand: THREE.Mesh;
		Cup: THREE.Mesh;
		CupHolder: THREE.Mesh;
		Rolls: THREE.Mesh;
		Frame: THREE.Mesh;
		Glass: THREE.Mesh;
		RoofLampEmission: THREE.Mesh;
		LeftLED: THREE.Mesh;
		RightLED: THREE.Mesh;
	};
	materials: object;
	animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
	const group = React.useRef<THREE.Group>(null);
	const { nodes, materials, animations } = useGLTF("/office-room.glb") as GLTFResult;
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Notebook" position={[3.812, 1.163, -2.692]} rotation={[-Math.PI, 1.558, -Math.PI]} scale={0.112}>
					<mesh
						name="Books"
						geometry={nodes.Books.geometry}
						material={nodes.Books.material}
						position={[0.049, 0.064, -0.017]}
						rotation={[3.135, 0, Math.PI]}
						scale={8.896}
					/>
				</group>
				<group name="PaperStack" position={[4.283, 1.443, -2.809]} rotation={[0, -0.156, 0]}>
					<mesh name="Paper" geometry={nodes.Paper.geometry} material={nodes.Paper.material} position={[0.089, -0.183, 0.294]} scale={[1, 0.01, 1]} />
				</group>
				<group name="Pen_holder_with_supplies" position={[4.768, 1.169, -2.744]}>
					<mesh name="PenHolderMesh" geometry={nodes.PenHolderMesh.geometry} material={nodes.PenHolderMesh.material} position={[-0.004, 0.048, 0]} />
				</group>
				<group name="Iphone_14_Pro(Space_Grey)" position={[6.408, 1.302, -1.846]} rotation={[1.204, -Math.PI / 2, 0]}>
					<mesh name="CameraOutline" geometry={nodes.CameraOutline.geometry} material={nodes.CameraOutline.material} position={[-0.05, -0.002, -0.013]} />
					<mesh name="iPhoneLences" geometry={nodes.iPhoneLences.geometry} material={nodes.iPhoneLences.material} position={[-0.05, 0.001, -0.004]} />
					<mesh name="MainPhoneCase" geometry={nodes.MainPhoneCase.geometry} material={nodes.MainPhoneCase.material} position={[-0.002, 0.009, 0]} />
				</group>
				<group name="Solder_roll" position={[-2.759, 2.769, 2.466]}>
					<mesh
						name="PLARollHolder"
						geometry={nodes.PLARollHolder.geometry}
						material={nodes.PLARollHolder.material}
						position={[0, 0.007, -0.023]}
						rotation={[0, 0, -Math.PI / 2]}>
						<mesh name="Solder_curve" geometry={nodes.Solder_curve.geometry} material={nodes.Solder_curve.material} />
						<mesh name="Solder_mesh" geometry={nodes.Solder_mesh.geometry} material={nodes.Solder_mesh.material} />
					</mesh>
				</group>
				<group name="Solder_roll007" position={[-2.986, 2.769, 2.466]}>
					<mesh
						name="Solder_roll006"
						geometry={nodes.Solder_roll006.geometry}
						material={nodes.Solder_roll006.material}
						position={[0, 0.007, -0.023]}
						rotation={[0, 0, -Math.PI / 2]}>
						<mesh name="Solder_curve003" geometry={nodes.Solder_curve003.geometry} material={nodes.Solder_curve003.material} />
						<mesh name="Solder_mesh003" geometry={nodes.Solder_mesh003.geometry} material={nodes.Solder_mesh003.material} />
					</mesh>
				</group>
				<group name="Solder_roll002" position={[-3.213, 2.769, 2.466]}>
					<mesh
						name="Solder_roll003"
						geometry={nodes.Solder_roll003.geometry}
						material={nodes.Solder_roll003.material}
						position={[0, 0.007, -0.023]}
						rotation={[0, 0, -Math.PI / 2]}>
						<mesh name="Solder_curve001" geometry={nodes.Solder_curve001.geometry} material={nodes.Solder_curve001.material} />
						<mesh name="Solder_mesh001" geometry={nodes.Solder_mesh001.geometry} material={nodes.Solder_mesh001.material} />
					</mesh>
				</group>
				<group name="Solder_roll005" position={[-3.442, 2.769, 2.466]}>
					<mesh
						name="Solder_roll004"
						geometry={nodes.Solder_roll004.geometry}
						material={nodes.Solder_roll004.material}
						position={[0, 0.007, -0.023]}
						rotation={[0, 0, -Math.PI / 2]}>
						<mesh name="Solder_curve002" geometry={nodes.Solder_curve002.geometry} material={nodes.Solder_curve002.material} />
						<mesh name="Solder_mesh002" geometry={nodes.Solder_mesh002.geometry} material={nodes.Solder_mesh002.material} />
					</mesh>
				</group>
				<group name="OldMacbook" position={[0.635, 0.066, -2.625]} scale={[0.8, 1.5, 0.8]}>
					<group name="OldMacbookScreenControlls" position={[0, 0.027, -0.265]} rotation={[1.506, 0, 0]} scale={0.259} />
					<mesh
						name="OldMacbookHousing"
						geometry={nodes.OldMacbookHousing.geometry}
						material={nodes.OldMacbookHousing.material}
						position={[0, 0.017, -0.003]}
						rotation={[-0.016, 0, 0]}
						scale={0.274}
					/>
				</group>
				<group name="BookControls" position={[-0.415, 0.953, -2.344]} scale={1.743}>
					<mesh
						name="BeigeBook"
						geometry={nodes.BeigeBook.geometry}
						material={nodes.BeigeBook.material}
						position={[0.23, 0.109, 0.004]}
						rotation={[1.562, 0.431, -1.548]}
					/>
					<mesh
						name="BlackBook"
						geometry={nodes.BlackBook.geometry}
						material={nodes.BlackBook.material}
						position={[0.008, 0.087, 0.014]}
						rotation={[1.571, 0.003, -1.57]}
					/>
					<mesh
						name="Cube107"
						geometry={nodes.Cube107.geometry}
						material={nodes.Cube107.material}
						position={[0.389, 0.112, 0.009]}
						rotation={[1.562, 0.482, -1.551]}
					/>
					<mesh
						name="Cube108"
						geometry={nodes.Cube108.geometry}
						material={nodes.Cube108.material}
						position={[0.421, 0.106, 0.003]}
						rotation={[1.579, 0.554, -1.559]}
					/>
					<mesh
						name="Cube109"
						geometry={nodes.Cube109.geometry}
						material={nodes.Cube109.material}
						position={[0.16, 0.1, 0.005]}
						rotation={[1.565, 0.418, -1.557]}
					/>
					<mesh
						name="Cube110"
						geometry={nodes.Cube110.geometry}
						material={nodes.Cube110.material}
						position={[0.14, 0.088, -0.003]}
						rotation={[1.567, 0.372, -1.562]}
					/>
					<mesh
						name="Cube111"
						geometry={nodes.Cube111.geometry}
						material={nodes.Cube111.material}
						position={[0.362, 0.114, 0.007]}
						rotation={[1.558, 0.479, -1.55]}
					/>
					<mesh
						name="Cube112"
						geometry={nodes.Cube112.geometry}
						material={nodes.Cube112.material}
						position={[0.108, 0.116, -0.003]}
						rotation={[1.57, 0.318, -1.57]}
					/>
					<mesh
						name="Cube113"
						geometry={nodes.Cube113.geometry}
						material={nodes.Cube113.material}
						position={[0.26, 0.111, 0.006]}
						rotation={[1.568, 0.439, -1.554]}
					/>
					<mesh
						name="Cube114"
						geometry={nodes.Cube114.geometry}
						material={nodes.Cube114.material}
						position={[0.277, 0.116, -0.002]}
						rotation={[1.566, 0.441, -1.555]}
					/>
					<mesh
						name="Cube116"
						geometry={nodes.Cube116.geometry}
						material={nodes.Cube116.material}
						position={[0.346, 0.098, -0.003]}
						rotation={[1.56, 0.461, -1.551]}
					/>
					<mesh
						name="Cube117"
						geometry={nodes.Cube117.geometry}
						material={nodes.Cube117.material}
						position={[0.322, 0.112, -0.001]}
						rotation={[1.565, 0.443, -1.553]}
					/>
					<mesh
						name="Cube118"
						geometry={nodes.Cube118.geometry}
						material={nodes.Cube118.material}
						position={[0.302, 0.114, 0.006]}
						rotation={[1.564, 0.444, -1.553]}
					/>
					<mesh
						name="Cube119"
						geometry={nodes.Cube119.geometry}
						material={nodes.Cube119.material}
						position={[0.099, 0.101, -0.002]}
						rotation={[1.572, 0.319, -1.571]}
					/>
					<mesh
						name="Cube122"
						geometry={nodes.Cube122.geometry}
						material={nodes.Cube122.material}
						position={[0.249, 0.108, 0.007]}
						rotation={[1.571, 0.439, -1.555]}
					/>
					<mesh
						name="Cube125"
						geometry={nodes.Cube125.geometry}
						material={nodes.Cube125.material}
						position={[0.206, 0.111, 0.001]}
						rotation={[1.563, 0.432, -1.552]}
					/>
					<mesh
						name="Cube126"
						geometry={nodes.Cube126.geometry}
						material={nodes.Cube126.material}
						position={[0.191, 0.107, 0.003]}
						rotation={[1.562, 0.429, -1.549]}
					/>
					<mesh
						name="GreenBook"
						geometry={nodes.GreenBook.geometry}
						material={nodes.GreenBook.material}
						position={[0.027, 0.1, 0.017]}
						rotation={[1.571, 0.003, -1.57]}
					/>
					<mesh
						name="GreyBook"
						geometry={nodes.GreyBook.geometry}
						material={nodes.GreyBook.material}
						position={[0.043, 0.1, 0.006]}
						rotation={[1.571, 0.003, -1.572]}
					/>
					<mesh
						name="RedBook"
						geometry={nodes.RedBook.geometry}
						material={nodes.RedBook.material}
						position={[0.18, 0.097, 0.007]}
						rotation={[1.563, 0.425, -1.553]}
					/>
					<mesh
						name="WhiteBook"
						geometry={nodes.WhiteBook.geometry}
						material={nodes.WhiteBook.material}
						position={[0.057, 0.091, 0.008]}
						rotation={[1.57, 0.005, -1.573]}
					/>
				</group>
				<group name="Musterbox" position={[-3.183, 2.269, -2.525]} rotation={[-Math.PI / 2, 0, -0.015]}>
					<group name="MusterboxControlls" position={[-0.002, 0.108, 0]} rotation={[0, 0, -Math.PI]}>
						<group
							name="Siebdruckfaecher_2021_Anim_PURE_No_Cor_V2_Mat_Red2"
							position={[-0.541, 0, 0.403]}
							rotation={[1.598, 0, 0]}
							scale={[0.011, 0.012, 0.012]}>
							<group name="Siebdruckfaecher_2021_Anim_PURE_No_Cor_V2" position={[30, -24, 0.755]} rotation={[0, 0, -Math.PI / 2]}>
								<group name="01" position={[0, 0.466, 0]}>
									<group name="Back024" position={[0, -0.015, 0]}>
										<group name="Back_2001">
											<group name="Node_361">
												<mesh name="MusterboxFaecher" geometry={nodes.MusterboxFaecher.geometry} material={nodes.MusterboxFaecher.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="02" position={[0, 0.436, 0]}>
									<group name="Back_3" position={[0, -0.015, 0]}>
										<group name="Back_4001">
											<group name="Node_370">
												<mesh name="MusterboxFaecherPages" geometry={nodes.MusterboxFaecherPages.geometry} material={nodes.MusterboxFaecherPages.material} />
											</group>
										</group>
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_01" position={[0.198, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group
								name="WG_BOX_Scene_2021_Animation_Oeffnen_Convertierte_Mat"
								position={[-0.09, -0.172, -0.006]}
								rotation={[0, 0, -Math.PI / 2]}
								scale={0.625}>
								<group name="Assembly-61" scale={0.01}>
									<group name="BODEN" rotation={[Math.PI / 2, 0, 0]}>
										<group name="WG_Box_1_3" position={[0.107, 0.08, -7.038]} rotation={[Math.PI, 0, Math.PI]}>
											<group name="Box_3" position={[0, -0.131, 7.607]} rotation={[-Math.PI / 2, 0, 0]}>
												<group name="Back_6">
													<group name="Node_62">
														<mesh name="MusterboxBoden" geometry={nodes.MusterboxBoden.geometry} material={nodes.MusterboxBoden.material} />
													</group>
												</group>
											</group>
											<group name="Inlay_3" position={[0, 0.131, -7.607]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
												<group name="Back_5">
													<group name="Node_52">
														<mesh name="MusterboxInside" geometry={nodes.MusterboxInside.geometry} material={nodes.MusterboxInside.material} />
													</group>
												</group>
											</group>
										</group>
									</group>
									<group name="DECKEL_M_LASCHE" position={[0, 20.691, 23.178]} rotation={[2.084, 0, 0]}>
										<group name="DECKEL" position={[0, -0.001, -0.004]}>
											<group name="Boole_1_2" position={[0, -23.278, 20.816]}>
												<group name="WG_Box_1_2" position={[0.107, 0.08, -7.038]} rotation={[Math.PI, 0, Math.PI]}>
													<group name="Box_2" position={[0, -0.131, 7.607]} rotation={[-Math.PI / 2, 0, 0]}>
														<group name="Back_4">
															<group name="Node_32">
																<mesh name="MusterboxDeckel" geometry={nodes.MusterboxDeckel.geometry} material={nodes.MusterboxDeckel.material} />
															</group>
														</group>
													</group>
												</group>
											</group>
											<group name="Cube_4" position={[0, 10.271, 18.825]} rotation={[0.759, 0, 0]}>
												<group name="Assembly-36">
													<group name="Node_43">
														<mesh
															name="MusterboxDeckelRightSide"
															geometry={nodes.MusterboxDeckelRightSide.geometry}
															material={nodes.MusterboxDeckelRightSide.material}
														/>
													</group>
												</group>
											</group>
										</group>
										<group name="LASCHE" position={[0, 30.714, -30.72]} rotation={[0.008, 0, 0]}>
											<group name="Boole_1" position={[0, -53.917, 51.551]}>
												<group name="WG_Box_1" position={[0.107, 0.08, -7.038]} rotation={[-Math.PI, 0, -Math.PI]}>
													<group name="Box" position={[0, -0.131, 7.607]} rotation={[-Math.PI / 2, 0, 0]}>
														<group name="Back_2">
															<group name="Node_15">
																<mesh name="MusterboxLasche" geometry={nodes.MusterboxLasche.geometry} material={nodes.MusterboxLasche.material} />
															</group>
														</group>
													</group>
												</group>
											</group>
											<group name="Cube_2" position={[0, -20.367, 49.56]} rotation={[0.759, 0, 0]}>
												<group name="Assembly-18">
													<group name="Node_22">
														<mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
													</group>
												</group>
											</group>
										</group>
									</group>
									<group name="GRIFF" position={[0, -2.672, 1.882]} rotation={[Math.PI / 2, 0, 0]}>
										<group name="Cylinder011" position={[0.004, 0, -2.601]}>
											<group name="Assembly-60">
												<group name="Node_79">
													<mesh name="MusterboxGriff" geometry={nodes.MusterboxGriff.geometry} material={nodes.MusterboxGriff.material} />
												</group>
											</group>
										</group>
									</group>
								</group>
							</group>
							<group name="WG_VAPack_2020_Muster_Orig_01001" scale={0.01}>
								<group name="Assembly-6">
									<group name="Node_83">
										<mesh name="MusterboxBox01" geometry={nodes.MusterboxBox01.geometry} material={nodes.MusterboxBox01.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_02_V2" position={[0.126, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_02_V2001" scale={0.01}>
								<group name="Assembly-6001">
									<group name="Node_94">
										<mesh name="MusterboxBox02" geometry={nodes.MusterboxBox02.geometry} material={nodes.MusterboxBox02.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_03_V3" position={[0.056, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_03_V3001" scale={0.01}>
								<group name="Assembly-6002">
									<group name="Node_105">
										<mesh name="MusterboxBox03" geometry={nodes.MusterboxBox03.geometry} material={nodes.MusterboxBox03.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_04_V3" position={[-0.019, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_04_V3001" scale={0.01}>
								<group name="Assembly-6003">
									<group name="Node_116">
										<mesh name="MusterboxBox04" geometry={nodes.MusterboxBox04.geometry} material={nodes.MusterboxBox04.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_05_Final_V3" position={[-0.09, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_05_Final_V3001" scale={0.01}>
								<group name="Assembly-6004">
									<group name="Node_127">
										<mesh name="MusterboxBox05" geometry={nodes.MusterboxBox05.geometry} material={nodes.MusterboxBox05.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_06_NEU" position={[-0.163, -0.004, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_06_NEU001" scale={0.01}>
								<group name="Assembly-6005">
									<group name="Node_138">
										<mesh name="MusterboxBox06" geometry={nodes.MusterboxBox06.geometry} material={nodes.MusterboxBox06.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_07" position={[0.198, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_07001" scale={0.01}>
								<group name="Assembly-6006">
									<group name="Node_149">
										<mesh name="MusterboxBox07" geometry={nodes.MusterboxBox07.geometry} material={nodes.MusterboxBox07.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_08" position={[0.126, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_08001" scale={0.01}>
								<group name="Assembly-6007">
									<group name="Node_160">
										<mesh name="MusterboxBox08" geometry={nodes.MusterboxBox08.geometry} material={nodes.MusterboxBox08.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_09" position={[0.056, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_09001" scale={0.01}>
								<group name="Assembly-6008">
									<group name="Node_171">
										<mesh name="MusterboxBox09" geometry={nodes.MusterboxBox09.geometry} material={nodes.MusterboxBox09.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_10" position={[-0.019, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_10001" scale={0.01}>
								<group name="Assembly-6009">
									<group name="Node_182">
										<mesh name="MusterboxBox10" geometry={nodes.MusterboxBox10.geometry} material={nodes.MusterboxBox10.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_11_V2" position={[-0.09, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_11_V2001" scale={0.01}>
								<group name="Assembly-6010">
									<group name="Node_193">
										<mesh name="MusterboxBox11" geometry={nodes.MusterboxBox11.geometry} material={nodes.MusterboxBox11.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_12" position={[-0.163, 0.067, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_12001" scale={0.01}>
								<group name="Assembly-6011">
									<group name="Node_204">
										<mesh name="MusterboxBox12" geometry={nodes.MusterboxBox12.geometry} material={nodes.MusterboxBox12.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_13" position={[0.198, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_13001" scale={0.01}>
								<group name="Assembly-6012">
									<group name="Node_215">
										<mesh name="MusterboxBox13" geometry={nodes.MusterboxBox13.geometry} material={nodes.MusterboxBox13.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_14_V2" position={[0.126, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_14_V2001" scale={0.01}>
								<group name="Assembly-6013">
									<group name="Node_226">
										<mesh name="MusterboxBox14" geometry={nodes.MusterboxBox14.geometry} material={nodes.MusterboxBox14.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_15" position={[0.056, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_15001" scale={0.01}>
								<group name="Assembly-6014">
									<group name="Node_237">
										<mesh name="MusterboxBox15" geometry={nodes.MusterboxBox15.geometry} material={nodes.MusterboxBox15.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_16" position={[-0.019, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_16001" scale={0.01}>
								<group name="Assembly-6015">
									<group name="Node_248">
										<mesh name="MusterboxBox16" geometry={nodes.MusterboxBox16.geometry} material={nodes.MusterboxBox16.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_17" position={[-0.09, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_17001" scale={0.01}>
								<group name="Assembly-6016">
									<group name="Node_259">
										<mesh name="MusterboxBox17" geometry={nodes.MusterboxBox17.geometry} material={nodes.MusterboxBox17.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_18" position={[-0.163, 0.138, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_18001" scale={0.01}>
								<group name="Assembly-6017">
									<group name="Node_270">
										<mesh name="MusterboxBox18" geometry={nodes.MusterboxBox18.geometry} material={nodes.MusterboxBox18.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_19_NEU" position={[0.198, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_19_NEU001" scale={0.01}>
								<group name="Assembly-6018">
									<group name="Node_281">
										<mesh name="MusterboxBox19" geometry={nodes.MusterboxBox19.geometry} material={nodes.MusterboxBox19.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_20" position={[0.126, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_20001" scale={0.01}>
								<group name="Assembly-6019">
									<group name="Node_292">
										<mesh name="MusterboxBox20" geometry={nodes.MusterboxBox20.geometry} material={nodes.MusterboxBox20.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_21" position={[0.056, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_21001" scale={0.01}>
								<group name="Assembly-6020">
									<group name="Node_303">
										<mesh name="MusterboxBox21" geometry={nodes.MusterboxBox21.geometry} material={nodes.MusterboxBox21.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_22" position={[-0.019, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_22001" scale={0.01}>
								<group name="Assembly-6021">
									<group name="Node_314">
										<mesh name="MusterboxBox22" geometry={nodes.MusterboxBox22.geometry} material={nodes.MusterboxBox22.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_23" position={[-0.09, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_23001" scale={0.01}>
								<group name="Assembly-6022">
									<group name="Node_325">
										<mesh name="MusterboxBox23" geometry={nodes.MusterboxBox23.geometry} material={nodes.MusterboxBox23.material} />
									</group>
								</group>
							</group>
						</group>
						<group name="WG_VAPack_2020_Muster_Orig_24" position={[-0.163, 0.212, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={1.149}>
							<group name="WG_VAPack_2020_Muster_Orig_24001" scale={0.01}>
								<group name="Assembly-6023">
									<group name="Node_336">
										<mesh name="MusterboxBox24" geometry={nodes.MusterboxBox24.geometry} material={nodes.MusterboxBox24.material} />
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
				<group name="AuxScene" position={[0.552, 2.297, -2.164]}>
					<group name="AuxContolls1" position={[0, 0, -0.277]}>
						<group name="AuxContolls2" rotation={[-Math.PI / 2, 0, 0]}>
							<group name="Kuehler_Final_Anim_SumLab_2024">
								<group name="Kuehler_Origami_20">
									<group name="Assembly-25_1" scale={0.01}>
										<group name="Tub" position={[0, 0, 0.489]} rotation={[0, 0, -Math.PI]}>
											<group name="Assembly-20">
												<group name="47cf6780-e790-4dc0-865b-199a5c697423">
													<mesh
														name="FCBoxKuehlerBottomPart"
														geometry={nodes.FCBoxKuehlerBottomPart.geometry}
														material={nodes.FCBoxKuehlerBottomPart.material}
													/>
												</group>
											</group>
											<group name="Back_3001">
												<group name="1f04486f-db53-4c8d-b66b-a832e8519c90">
													<mesh name="FCBoxKuehlerBackPart" geometry={nodes.FCBoxKuehlerBackPart.geometry} material={nodes.FCBoxKuehlerBackPart.material} />
												</group>
											</group>
											<group name="Side_3">
												<group name="20c8b3c8-2579-46de-8dd4-3d65938e8636">
													<mesh name="FCBoxKuehlerSidePart" geometry={nodes.FCBoxKuehlerSidePart.geometry} material={nodes.FCBoxKuehlerSidePart.material} />
												</group>
											</group>
										</group>
									</group>
								</group>
								<group name="SENOLITH_WB" position={[0, -0.113, -0.222]} rotation={[0, 0, Math.PI / 2]}>
									<group name="3DGeom-5" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="b9851b43-7947-4929-b103-33c105404562" />
									</group>
									<group name="Draht" position={[-0.403, 0, 0.28]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="3a05e130-1f3d-4268-b45b-cfc9c0a23ff4">
												<mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOLITH_WB-2" position={[0, -0.113, -0.097]} rotation={[0, 0, Math.PI / 2]}>
									<group name="3DGeom-5_5" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="80e52696-1d56-440e-957a-75538ee040d3" />
									</group>
									<group name="Draht_1" position={[-0.403, 0, 0.28]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_5" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="f6ffb633-f7c9-4f8b-8992-cf5c37dba7cd">
												<mesh name="mesh_11" geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOLITH_WB-3" position={[0.113, 0, -0.227]} rotation={[0, 0, Math.PI]}>
									<group name="3DGeom-5_6" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="9e16782a-b948-417c-8fae-1a03457cdde4">
											<mesh name="mesh_12" geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
										</group>
									</group>
									<group name="Draht_2" position={[-0.403, 0, 0.28]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_6" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="7c3f4d97-b3fa-40c2-b2fa-906caf130873" position={[0.002, 0, 0]}>
												<mesh name="mesh_13" geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} position={[0.002, 0, 0]} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOLITH_WB-4" position={[0.113, 0, -0.224]} rotation={[0, 0, Math.PI]}>
									<group name="3DGeom-5_7" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="bbab0546-663f-4280-982d-1b5e5dc54510">
											<mesh name="mesh_14" geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
										</group>
									</group>
									<group name="Draht_3" position={[-0.403, 0, 0.28]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_7" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="63e44809-d8ae-4ce6-a44a-900cce9460cf" position={[0.001, 0, 0]}>
												<mesh name="mesh_15" geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} position={[0.001, 0, 0]} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOSCREEN" position={[0.113, 0, -0.222]} rotation={[0, 0, Math.PI]}>
									<group name="3DGeom-5_2" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="d8709e38-ee04-42f3-a36f-ee26ae8722cc">
											<mesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
										</group>
									</group>
									<group name="Draht-6" position={[-0.403, 0, 0.279]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_2" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="e9f01260-0fba-4efb-ad01-ef23c62a6831" position={[0.002, 0, 0]}>
												<mesh name="mesh_5" geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} position={[0.002, 0, 0]} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOSCREEN-2" position={[0.113, 0, -0.097]} rotation={[0, 0, Math.PI]}>
									<group name="3DGeom-5_9" position={[0.163, 0, 0.279]} scale={[0.033, 0.001, 0.05]}>
										<group name="13f34bb3-8479-4aed-baad-73b330760289" />
									</group>
									<group name="Draht-6_1" position={[-0.403, 0, 0.279]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_9" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="4345f071-191f-4dda-bc2d-f03bee49eb4e" position={[0.002, 0, 0]}>
												<mesh name="mesh_19" geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} position={[0.002, 0, 0]} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOSOFT" position={[-0.113, 0, -0.164]}>
									<group name="3DGeom-5_1" position={[0.163, 0, 0.221]} scale={[0.033, 0.001, 0.05]}>
										<group name="07e7ac20-c07b-476e-b16e-a0d117137e44">
											<mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
										</group>
									</group>
									<group name="Draht-5" position={[-0.403, 0, 0.221]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_1" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="f0005f01-0f24-4332-8c3e-2f9bf869bc6f">
												<mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="SENOSOFT-2" position={[-0.113, 0, -0.039]}>
									<group name="3DGeom-5_8" position={[0.163, 0, 0.221]} scale={[0.033, 0.001, 0.05]}>
										<group name="79e9acba-4949-4b96-bb13-951d0418995f" />
									</group>
									<group name="Draht-5_1" position={[-0.403, 0, 0.221]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_8" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="c89bd378-9fdb-4914-b081-247f5553359c">
												<mesh name="mesh_17" geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="Waterproof" position={[-0.114, 0, -0.102]}>
									<group name="3DGeom-5_3" position={[0.163, 0, 0.157]} scale={[0.033, 0.001, 0.05]}>
										<group name="007e2a65-c98e-42d4-b415-876f31451ff7">
											<mesh name="mesh_6" geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
										</group>
									</group>
									<group name="Draht-7" position={[-0.4, 0, 0.16]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_3" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="0821fe24-93d5-4b89-a71b-13e20a9fe40a">
												<mesh name="mesh_7" geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="Waterproof-2" position={[-0.114, 0, -0.105]}>
									<group name="3DGeom-5_4" position={[0.163, 0, 0.157]} scale={[0.033, 0.001, 0.05]}>
										<group name="001e9279-9a8a-4069-a011-b5ef36f30b55">
											<mesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
										</group>
									</group>
									<group name="Draht-7_1" position={[-0.4, 0, 0.16]} rotation={[0, 1.571, 0]}>
										<group name="3DGeom-6_4" position={[0, 0, 0.5]} scale={[0, 0, 0.1]}>
											<group name="071b54d1-748f-49b5-bfb2-265f20b0062f">
												<mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
											</group>
										</group>
									</group>
								</group>
								<group name="Kuehler_Origami_16" position={[0, 0, 0.004]}>
									<group name="Assembly-25" scale={0.01}>
										<group name="Divider" position={[0, 0, 9.255]} rotation={[-Math.PI, 0, -Math.PI]}>
											<group name="Assembly-14">
												<group name="3657fd27-c385-456c-bba8-88da6f6dd94c">
													<mesh name="FCBoxDBottomPart" geometry={nodes.FCBoxDBottomPart.geometry} material={nodes.FCBoxDBottomPart.material} />
												</group>
											</group>
											<group name="Back_2002">
												<group name="fde87e1f-fbda-4d20-ae33-e67fe6466ae1">
													<mesh name="FCBoxDBackPart" geometry={nodes.FCBoxDBackPart.geometry} material={nodes.FCBoxDBackPart.material} />
												</group>
											</group>
											<group name="Side_2001">
												<group name="2f5c5851-1bb1-475d-9d3c-b74584a30164">
													<mesh name="FCBoxDSidePart" geometry={nodes.FCBoxDSidePart.geometry} material={nodes.FCBoxDSidePart.material} />
												</group>
											</group>
										</group>
										<group name="Head" position={[-0.05, 0, 24.073]} rotation={[-Math.PI, 0, 0]}>
											<group name="Assembly-8001" position={[0, 0, 9.101]}>
												<group name="d82db677-5f70-45af-a1af-fa2b0c8230ad">
													<mesh name="FCBoxHBottomPart" geometry={nodes.FCBoxHBottomPart.geometry} material={nodes.FCBoxHBottomPart.material} />
												</group>
											</group>
											<group name="Back_1" position={[0, 0, 9.101]}>
												<group name="dda4fdb3-dc08-4bc1-a19e-999cd9176569">
													<mesh name="FCBoxHBackPart" geometry={nodes.FCBoxHBackPart.geometry} material={nodes.FCBoxHBackPart.material} />
												</group>
											</group>
											<group name="Side_1" position={[0, 0, 9.101]}>
												<group name="0539de86-5467-4162-b702-5b5745e9941a">
													<mesh name="FCBoxHSidePart" geometry={nodes.FCBoxHSidePart.geometry} material={nodes.FCBoxHSidePart.material} />
												</group>
											</group>
										</group>
										<group name="Bottom" rotation={[0, 0, -Math.PI]}>
											<group name="Assembly-2">
												<group name="42d8f6c3-69ca-4867-a2fc-18b072e7ef8e">
													<mesh name="FCBoxBBottomPart" geometry={nodes.FCBoxBBottomPart.geometry} material={nodes.FCBoxBBottomPart.material} />
												</group>
											</group>
											<group name="Back025">
												<group name="6d3ca46c-8d73-498e-8d6a-3af0c25f4e3f">
													<mesh name="FCBoxBBackPart" geometry={nodes.FCBoxBBackPart.geometry} material={nodes.FCBoxBBackPart.material} />
												</group>
											</group>
											<group name="Side024">
												<group name="1b0d75ce-e233-4884-bd8a-8625309af3b3">
													<mesh name="FCBoxBSidePart" geometry={nodes.FCBoxBSidePart.geometry} material={nodes.FCBoxBSidePart.material} />
												</group>
											</group>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
				<group name="Vase_with_dried_flowers" position={[7.519, 1.322, 0.941]}>
					<mesh
						name="Flower1"
						geometry={nodes.Flower1.geometry}
						material={nodes.Flower1.material}
						position={[0.107, 0.529, -0.054]}
						rotation={[3.087, 0.387, -3.024]}
					/>
					<mesh name="Flower2" geometry={nodes.Flower2.geometry} material={nodes.Flower2.material} position={[-0.021, 0.446, -0.141]} />
					<mesh
						name="Flower3"
						geometry={nodes.Flower3.geometry}
						material={nodes.Flower3.material}
						position={[0.149, 0.496, 0.064]}
						rotation={[Math.PI, -1.155, Math.PI]}
					/>
					<mesh name="Flower4" geometry={nodes.Flower4.geometry} material={nodes.Flower4.material} position={[-0.061, 0.583, 0.088]} />
					<mesh name="vase" geometry={nodes.vase.geometry} material={nodes.vase.material} position={[0, 0.106, 0]} />
				</group>
				<group name="Floor_Lamp" position={[1.852, 0.687, -2.602]}>
					<mesh name="FloorLamp_Bulb" geometry={nodes.FloorLamp_Bulb.geometry} material={nodes.FloorLamp_Bulb.material} />
					<mesh name="FloorLamp_Cover" geometry={nodes.FloorLamp_Cover.geometry} material={nodes.FloorLamp_Cover.material} position={[0, 1.368, 0]} />
					<mesh name="FloorLamp_Stem" geometry={nodes.FloorLamp_Stem.geometry} material={nodes.FloorLamp_Stem.material} />
				</group>
				<mesh name="Room" geometry={nodes.Room.geometry} material={nodes.Room.material} />
				<mesh name="Floor" geometry={nodes.Floor.geometry} material={nodes.Floor.material} position={[0, 0.01, 0]} />
				<mesh name="BackWall" geometry={nodes.BackWall.geometry} material={nodes.BackWall.material} />
				<mesh name="FrontWall" geometry={nodes.FrontWall.geometry} material={nodes.FrontWall.material} />
				<mesh name="WindowWall" geometry={nodes.WindowWall.geometry} material={nodes.WindowWall.material} />
				<mesh name="Roof" geometry={nodes.Roof.geometry} material={nodes.Roof.material} position={[0, -0.01, 0]} />
				<mesh name="LeftWall" geometry={nodes.LeftWall.geometry} material={nodes.LeftWall.material} />
				<mesh name="DeskWorkingAreas" geometry={nodes.DeskWorkingAreas.geometry} material={nodes.DeskWorkingAreas.material} position={[-6.451, 0.079, 0]} />
				<mesh
					name="DeskStands"
					geometry={nodes.DeskStands.geometry}
					material={nodes.DeskStands.material}
					position={[0.126, 0.477, 2.212]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh name="CupboardDoors" geometry={nodes.CupboardDoors.geometry} material={nodes.CupboardDoors.material} position={[1.954, 0.474, 2.239]} />
				<mesh name="CupboardOpeners" geometry={nodes.CupboardOpeners.geometry} material={nodes.CupboardOpeners.material} position={[-2.004, 1.407, -2.073]} />
				<mesh name="Ventilation" geometry={nodes.Ventilation.geometry} material={nodes.Ventilation.material} position={[5.24, 1.185, -1.726]} />
				<mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={nodes.Keyboard.material} position={[5.646, 1.186, -1.607]} />
				<mesh name="Screen" geometry={nodes.Screen.geometry} material={nodes.Screen.material} position={[5.641, 1.173, -1.776]} rotation={[1.333, 0, 0]} />
				<mesh name="Housing" geometry={nodes.Housing.geometry} material={nodes.Housing.material} position={[5.641, 1.176, -1.517]} rotation={[-0.016, 0, 0]} />
				<mesh name="Sit" geometry={nodes.Sit.geometry} material={nodes.Sit.material} position={[5.761, 1.063, -0.393]} rotation={[Math.PI, -0.147, Math.PI]}>
					<mesh
						name="Cube017"
						geometry={nodes.Cube017.geometry}
						material={nodes.Cube017.material}
						position={[0.163, 0.574, -0.563]}
						rotation={[-0.196, 0.026, -0.02]}
					/>
					<mesh
						name="Cube018_1"
						geometry={nodes.Cube018_1.geometry}
						material={nodes.Cube018_1.material}
						position={[0.163, 0.574, -0.563]}
						rotation={[-0.196, 0.026, -0.02]}
					/>
					<mesh
						name="Cube019"
						geometry={nodes.Cube019.geometry}
						material={nodes.Cube019.material}
						position={[-0.148, 0.572, -0.564]}
						rotation={[-0.196, 0.026, -0.02]}
					/>
					<mesh
						name="Cube020"
						geometry={nodes.Cube020.geometry}
						material={nodes.Cube020.material}
						position={[-0.148, 0.572, -0.564]}
						rotation={[-0.196, 0.026, -0.02]}
					/>
					<mesh
						name="Cube021_1"
						geometry={nodes.Cube021_1.geometry}
						material={nodes.Cube021_1.material}
						position={[0.001, 0.718, -0.583]}
						rotation={[0, 0.023, 0]}
					/>
					<mesh name="Cube029" geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[0.007, 0.261, 0.194]} />
					<mesh name="Cube030" geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[0, 0.017, 0.194]} />
					<mesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={nodes.Cube031_1.material} position={[0, 0.023, 0]} />
					<mesh name="Handle002" geometry={nodes.Handle002.geometry} material={nodes.Handle002.material} position={[0, 0.092, 0]} />
					<mesh
						name="Plane006"
						geometry={nodes.Plane006.geometry}
						material={nodes.Plane006.material}
						position={[0.137, 0.688, 0.011]}
						rotation={[Math.PI / 2, 0, 0.051]}
					/>
					<mesh
						name="Plane007"
						geometry={nodes.Plane007.geometry}
						material={nodes.Plane007.material}
						position={[0.004, 0.741, -0.53]}
						rotation={[Math.PI / 2, 0, 0.051]}
					/>
				</mesh>
				<mesh
					name="RightBackrestStrap"
					geometry={nodes.RightBackrestStrap.geometry}
					material={nodes.RightBackrestStrap.material}
					position={[5.453, 1.063, -0.347]}
					rotation={[Math.PI / 2, 0, 2.995]}
				/>
				<mesh
					name="LeftBackrestStrap"
					geometry={nodes.LeftBackrestStrap.geometry}
					material={nodes.LeftBackrestStrap.material}
					position={[5.761, 1.063, -0.393]}
					rotation={[Math.PI / 2, 0, 2.995]}
				/>
				<mesh
					name="Backrest"
					geometry={nodes.Backrest.geometry}
					material={nodes.Backrest.material}
					position={[5.761, 1.062, -0.395]}
					rotation={[Math.PI / 2, 0, 2.995]}
				/>
				<mesh
					name="BackrestController"
					geometry={nodes.BackrestController.geometry}
					material={nodes.BackrestController.material}
					position={[5.337, 0.743, -0.266]}
					rotation={[Math.PI, -0.418, Math.PI]}
				/>
				<mesh
					name="ChairStand"
					geometry={nodes.ChairStand.geometry}
					material={nodes.ChairStand.material}
					position={[5.761, 0.314, -0.393]}
					rotation={[Math.PI, -0.147, Math.PI]}
				/>
				<mesh
					name="BackrestPillow"
					geometry={nodes.BackrestPillow.geometry}
					material={nodes.BackrestPillow.material}
					position={[5.831, 1.804, 0.025]}
					rotation={[3.1, -0.147, 3.135]}
				/>
				<mesh
					name="ChairRoll"
					geometry={nodes.ChairRoll.geometry}
					material={nodes.ChairRoll.material}
					position={[5.854, 1.179, -0.811]}
					rotation={[Math.PI, 0.203, -Math.PI / 2]}
				/>
				<mesh name="Organizer" geometry={nodes.Organizer.geometry} material={nodes.Organizer.material} position={[4.324, 1.176, -1.82]} />
				<mesh name="Base" geometry={nodes.Base.geometry} material={nodes.Base.material} position={[6.408, 1.186, -1.805]} rotation={[0, -1.56, 0]} />
				<mesh
					name="FirstController"
					geometry={nodes.FirstController.geometry}
					material={nodes.FirstController.material}
					position={[3.575, 1.213, -1.762]}
					rotation={[1.586, -0.002, 0.363]}
				/>
				<mesh
					name="FrontOcculus"
					geometry={nodes.FrontOcculus.geometry}
					material={nodes.FrontOcculus.material}
					position={[3.405, 1.266, -1.468]}
					rotation={[-1.692, -0.081, 0.591]}
				/>
				<mesh
					name="BackOcculus"
					geometry={nodes.BackOcculus.geometry}
					material={nodes.BackOcculus.material}
					position={[3.405, 1.266, -1.468]}
					rotation={[-1.692, -0.081, 0.591]}
				/>
				<mesh
					name="bambuLabFrontDoor"
					geometry={nodes.bambuLabFrontDoor.geometry}
					material={nodes.bambuLabFrontDoor.material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c-ui"
					geometry={nodes["bambu-lab-x1c-ui"].geometry}
					material={nodes["bambu-lab-x1c-ui"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c-ui-display"
					geometry={nodes["bambu-lab-x1c-ui-display"].geometry}
					material={nodes["bambu-lab-x1c-ui-display"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c"
					geometry={nodes["bambu-lab-x1c"].geometry}
					material={nodes["bambu-lab-x1c"].material}
					position={[-2.564, 1.624, 2.522]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={1.871}
				/>
				<mesh
					name="bambu-lab-x1c-logo"
					geometry={nodes["bambu-lab-x1c-logo"].geometry}
					material={nodes["bambu-lab-x1c-logo"].material}
					position={[-2.564, 1.624, 2.522]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={1.871}
				/>
				<mesh
					name="bambuLabAMS"
					geometry={nodes.bambuLabAMS.geometry}
					material={nodes.bambuLabAMS.material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambuLabAMSTop"
					geometry={nodes.bambuLabAMSTop.geometry}
					material={nodes.bambuLabAMSTop.material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="PLARoll"
					geometry={nodes.PLARoll.geometry}
					material={nodes.PLARoll.material}
					position={[-2.763, 2.289, 2.378]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="SecondRoll001"
					geometry={nodes.SecondRoll001.geometry}
					material={nodes.SecondRoll001.material}
					position={[-2.99, 2.289, 2.378]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="SecondRoll002"
					geometry={nodes.SecondRoll002.geometry}
					material={nodes.SecondRoll002.material}
					position={[-3.217, 2.289, 2.378]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="SecondRoll003"
					geometry={nodes.SecondRoll003.geometry}
					material={nodes.SecondRoll003.material}
					position={[-3.446, 2.289, 2.378]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="bambu-lab-x1c-nozzle"
					geometry={nodes["bambu-lab-x1c-nozzle"].geometry}
					material={nodes["bambu-lab-x1c-nozzle"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c-nozzle-spike"
					geometry={nodes["bambu-lab-x1c-nozzle-spike"].geometry}
					material={nodes["bambu-lab-x1c-nozzle-spike"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c--nozzle-rods"
					geometry={nodes["bambu-lab-x1c--nozzle-rods"].geometry}
					material={nodes["bambu-lab-x1c--nozzle-rods"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="bambu-lab-x1c-nozzle-hole"
					geometry={nodes["bambu-lab-x1c-nozzle-hole"].geometry}
					material={nodes["bambu-lab-x1c-nozzle-hole"].material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="FolderDocuments"
					geometry={nodes.FolderDocuments.geometry}
					material={nodes.FolderDocuments.material}
					position={[0.112, 1.591, -2.345]}
					rotation={[0, 0, -0.43]}
				/>
				<mesh
					name="Pool_balls_set"
					geometry={nodes.Pool_balls_set.geometry}
					material={nodes.Pool_balls_set.material}
					position={[-6.451, 2.505, -1.76]}
					rotation={[0, -1.127, 0]}
					scale={0.472}
				/>
				<mesh name="RoofLamp" geometry={nodes.RoofLamp.geometry} material={nodes.RoofLamp.material} position={[0, 5.267, 0]} rotation={[0, 0, Math.PI]} />
				<mesh name="DoorBase" geometry={nodes.DoorBase.geometry} material={nodes.DoorBase.material} position={[4, 1.948, 2.942]} />
				<mesh
					name="MainHandle"
					geometry={nodes.MainHandle.geometry}
					material={nodes.MainHandle.material}
					position={[3.394, 1.664, 2.88]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<mesh name="WindowBorder" geometry={nodes.WindowBorder.geometry} material={nodes.WindowBorder.material} position={[8.068, 2.323, 0.027]} />
				<mesh name="WindowGlass" geometry={nodes.WindowGlass.geometry} material={nodes.WindowGlass.material} position={[8.068, 2.323, 0.027]} />
				<mesh name="Filing" geometry={nodes.Filing.geometry} material={nodes.Filing.material} position={[7.509, 1.237, -0.012]} />
				<mesh name="CoffeCupStand" geometry={nodes.CoffeCupStand.geometry} material={nodes.CoffeCupStand.material} position={[7.516, 1.236, -0.849]} />
				<mesh name="Cup" geometry={nodes.Cup.geometry} material={nodes.Cup.material} position={[7.532, 1.357, -0.858]} rotation={[-Math.PI, 0, Math.PI / 2]} />
				<mesh
					name="CupHolder"
					geometry={nodes.CupHolder.geometry}
					material={nodes.CupHolder.material}
					position={[7.532, 1.361, -0.754]}
					rotation={[-Math.PI, 0, Math.PI / 2]}
					scale={[1, 3.689, 1]}
				/>
				<mesh
					name="Rolls"
					geometry={nodes.Rolls.geometry}
					material={nodes.Rolls.material}
					position={[2.327, 0.106, 1.998]}
					rotation={[Math.PI, -0.96, Math.PI]}
				/>
				<mesh
					name="Frame"
					geometry={nodes.Frame.geometry}
					material={nodes.Frame.material}
					position={[0.969, 2.976, 2.941]}
					rotation={[0, 1.571, 0]}
					scale={[1.9, 1, 1]}
				/>
				<mesh
					name="Glass"
					geometry={nodes.Glass.geometry}
					material={nodes.Glass.material}
					position={[0.969, 2.976, 2.941]}
					rotation={[0, 1.571, 0]}
					scale={[1.9, 1, 1]}
				/>
				<mesh
					name="RoofLampEmission"
					geometry={nodes.RoofLampEmission.geometry}
					material={nodes.RoofLampEmission.material}
					position={[0, 4.233, 0]}
					rotation={[0, 0, Math.PI]}
				/>
				<mesh
					name="LeftLED"
					geometry={nodes.LeftLED.geometry}
					material={nodes.LeftLED.material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
				<mesh
					name="RightLED"
					geometry={nodes.RightLED.geometry}
					material={nodes.RightLED.material}
					position={[-2.985, 2.243, 2.234]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.113}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/office-room.glb");
